#
# Makefile for FIRTEZ-dz
#-------------------------------------------
# A. Pastor Yabar & J. M. Borrero ; 2021 May
#
#
#===========================================
# To be edited by the USER:
#
LIBS = 

#
INCS = 
#
LDFLAGS = 
#
#===========================================
# From here on, you should not need to edit anything...
#
.PHONY: clean FIRTEZ-dz
.DEFAULT_GOAL := FIRTEZ-dz
#
# Common to both compilers
# 
FOPT=-O3 -fopenmp -std=legacy
F90F = -c
F77F = -c
#
#
# Compiler dependent:
# 
ifeq ($(COMP),intel)
# Intel compiler:
  #FC = mpiifort
  FC = mpif90
  #CC = mpiicc
#
  FPP = -fpp
  # Debugging: FOPT = -fopenmp -traceback -debug all -check all -g -O0
#
  FR8 = -r8
#
else
# Gfortran compiler:
  FC = mpif90
  #CC = mpicc
#
  FPP = -cpp
  # Debugging: FOPT = -fopenmp -fbacktrace -Wall -fcheck=all -g -finit-real=nan -finit-integer=0 -O0
#
  FR8 = -fdefault-real-8
#
endif

#
#

OBJ = \
	checknan.o \
	code_modes.o \
	cons_param.o \
	lm.o \
	user_mpi.o \
	voigt.o \
	allocate_utils.o \
	atom_database.o \
	coupled_param.o \
	derivvar.o \
	forward_param.o \
	grid_param.o \
	height_handler.o \
	invert_param.o \
	log.o \
	magsplit.o \
	misc.o \
	phys_param.o \
	time_param.o \
	user_fftw3.o \
	atm_param.o \
	chemical_equilibrium.o \
	cont_opacity.o \
	coupled_inversion.o \
	coupled_matrix_inversion.o \
	damping.o \
	get_dmodel.o \
	hydrostatic_tools.o \
	join_model.o \
	line_opacity.o \
	lines_database.o \
	model_spatial_extension.o \
	normalization.o \
	absorption_matrix.o \
	input_file.o \
	pre_post_duties.o \
	rtesolver.o \
	forward.o \
	invert3d.o \
	main.o

checknan.o: checknan.f90
	$(FC) $(F90F) $(FOPT) checknan.f90

code_modes.o: code_modes.f90
	$(FC) $(F90F) $(FOPT) code_modes.f90

cons_param.o: cons_param.f90
	$(FC) $(F90F) $(FOPT) cons_param.f90

lm.o: lm.f90
	$(FC) $(F90F) $(FOPT) lm.f90

user_mpi.o: user_mpi.f90
	$(FC) $(FPP) $(F90F) $(FOPT) user_mpi.f90

voigt.o: voigt.f
	$(FC) $(F77F) $(FOPT) $(FR8) voigt.f

allocate_utils.o: allocate_utils.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) allocate_utils.f90

atom_database.o: atom_database.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) atom_database.f90

coupled_param.o: coupled_param.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) coupled_param.f90

derivvar.o: derivvar.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) derivvar.f90

forward_param.o: forward_param.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) forward_param.f90

grid_param.o: grid_param.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) grid_param.f90

height_handler.o: height_handler.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) height_handler.f90

invert_param.o: invert_param.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) invert_param.f90

log.o: log.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) log.f90

magsplit.o: magsplit.f90 cons_param.o forward_param.o code_modes.o \
	allocate_utils.o
	$(FC) $(F90F) $(FOPT) magsplit.f90

misc.o: misc.f90 cons_param.o allocate_utils.o
	$(FC) $(F90F) $(FOPT) misc.f90

phys_param.o: phys_param.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) phys_param.f90

time_param.o: time_param.f90 cons_param.o
	$(FC) $(F90F) $(FOPT) time_param.f90

user_fftw3.o: user_fftw3.f90 cons_param.o
	$(FC) $(FPP) $(F90F) $(FOPT) $(INCS) user_fftw3.f90

atm_param.o: atm_param.f90 forward_param.o cons_param.o grid_param.o
	$(FC) $(F90F) $(FOPT) atm_param.f90

chemical_equilibrium.o: chemical_equilibrium.f90 cons_param.o atom_database.o \
	derivvar.o forward_param.o invert_param.o code_modes.o
	$(FC) $(F90F) $(FOPT) chemical_equilibrium.f90

cont_opacity.o: cont_opacity.f90 cons_param.o derivvar.o \
	chemical_equilibrium.o code_modes.o
	$(FC) $(F90F) $(FOPT) cont_opacity.f90

coupled_inversion.o: coupled_inversion.f90 coupled_param.o invert_param.o \
	grid_param.o forward_param.o allocate_utils.o user_mpi.o
	$(FC) $(F90F) $(FOPT) coupled_inversion.f90

coupled_matrix_inversion.o: coupled_matrix_inversion.f90 cons_param.o \
	allocate_utils.o misc.o
	$(FC) $(F90F) $(FOPT) coupled_matrix_inversion.f90

damping.o: damping.f90 cons_param.o atom_database.o derivvar.o code_modes.o \
	user_mpi.o
	$(FC) $(F90F) $(FOPT) damping.f90

get_dmodel.o: get_dmodel.f90 user_mpi.o code_modes.o cons_param.o \
	grid_param.o phys_param.o forward_param.o invert_param.o atm_param.o \
	height_handler.o allocate_utils.o lm.o misc.o
	$(FC) $(F90F) $(FOPT) get_dmodel.f90

hydrostatic_tools.o: hydrostatic_tools.f90 cons_param.o \
	chemical_equilibrium.o allocate_utils.o
	$(FC) $(F90F) $(FOPT) hydrostatic_tools.f90

join_model.o: join_model.f90 cons_param.o grid_param.o phys_param.o \
	forward_param.o
	$(FC) $(F90F) $(FOPT) join_model.f90

line_opacity.o: line_opacity.f90 cons_param.o atom_database.o derivvar.o \
	chemical_equilibrium.o code_modes.o forward_param.o
	$(FC) $(F90F) $(FOPT) line_opacity.f90

lines_database.o: lines_database.f90 user_mpi.o cons_param.o forward_param.o \
	allocate_utils.o log.o damping.o code_modes.o
	$(FC) $(F90F) $(FOPT) lines_database.f90

model_spatial_extension.o: model_spatial_extension.f90 user_mpi.o \
	cons_param.o grid_param.o allocate_utils.o forward_param.o invert_param.o \
	phys_param.o user_fftw3.o
	$(FC) $(F90F) $(FOPT) model_spatial_extension.f90

normalization.o: normalization.f90 cons_param.o forward_param.o \
	chemical_equilibrium.o allocate_utils.o cont_opacity.o
	$(FC) $(F90F) $(FOPT) normalization.f90

absorption_matrix.o: absorption_matrix.f90 cons_param.o derivvar.o \
	forward_param.o atm_param.o magsplit.o code_modes.o allocate_utils.o \
	atom_database.o
	$(FC) $(F90F) $(FOPT) absorption_matrix.f90

input_file.o: input_file.f90 cons_param.o user_mpi.o code_modes.o \
	invert_param.o forward_param.o grid_param.o allocate_utils.o \
	lines_database.o misc.o coupled_param.o
	$(FC) $(F90F) $(FOPT) input_file.f90

pre_post_duties.o: pre_post_duties.f90 cons_param.o atom_database.o log.o \
	lines_database.o input_file.o user_mpi.o time_param.o forward_param.o misc.o \
	phys_param.o code_modes.o grid_param.o user_fftw3.o allocate_utils.o \
	invert_param.o normalization.o coupled_inversion.o coupled_param.o \
	absorption_matrix.o
	$(FC) $(F90F) $(FOPT) pre_post_duties.f90

rtesolver.o: rtesolver.f90 cons_param.o atm_param.o absorption_matrix.o \
	phys_param.o code_modes.o grid_param.o invert_param.o forward_param.o
	$(FC) $(F90F) $(FOPT) rtesolver.f90

forward.o: forward.f90 cons_param.o time_param.o user_mpi.o grid_param.o \
	phys_param.o invert_param.o forward_param.o code_modes.o height_handler.o \
	user_fftw3.o rtesolver.o line_opacity.o cont_opacity.o damping.o \
	absorption_matrix.o atm_param.o hydrostatic_tools.o chemical_equilibrium.o
	$(FC) $(F90F) $(FOPT) forward.f90

invert3d.o: invert3d.f90 code_modes.o invert_param.o forward.o user_mpi.o \
	misc.o model_spatial_extension.o get_dmodel.o grid_param.o cons_param.o \
	phys_param.o forward_param.o allocate_utils.o coupled_inversion.o \
	height_handler.o user_fftw3.o
	$(FC) $(F90F) $(FOPT) invert3d.f90

main.o: main.f90 user_mpi.o pre_post_duties.o invert3d.o
	$(FC) $(F90F) $(FOPT) main.f90


FIRTEZ-dz: $(OBJ)
	$(FC) $(OBJ) $(LDFLAGS) $(LIBS) -o FIRTEZ-dz.x -fopenmp


clean:
	rm -f *.o *.mod *.x
